### PR TITLE
Refactor data flow to minimise duplicate state

### PR DESCRIPTION
**Pull request by fedde-s**
Using on the `value` property directly allows the component to no longer keep an `isSelected` flag updated in option objects, which simplifies the code substantially. Once this has been factored out, it can also benefit from the toggling functionality built into the underlying **react-select** component instead of a custom `onChange` handler. None of this should affect the functionality in any way, but it does require an update to the current release of **react-select**.

### CODE REVIEW

**Comment by fedde-s** [comment]
@rnugraha, could you review whether you agree with this refactoring, and especially whether the dependency version upgrade is correct?

**Comment by fedde-s** [comment]
The `npm` command seems to want me to update `package-lock.json` as well now that the dependencies have changed. should I include that change in the commit?

**Comment by rnugraha** [comment]
Please commit package-lock.json as well

**Comment by fedde-s** [comment]
I updated `package-lock.json`, and rebased the patches to resolve the merge conflicts.

**Comment by pieterlukasse** [comment]
@rnugraha is this ready to be merged?

**Comment by rnugraha** [comment]
Will close this since this is no longer necessary

**Comment by fedde-s** [comment]
I think it is as necessary as it ever was, to make the component easier to improve on and potentially more accessible.

**Comment by rnugraha** [comment]
@fedde-s  Okay, looks good. One more thing can u rebase/merge solve conflicts?

**Review by rnugraha — CHANGES_REQUESTED** [review]
Looks good. Pls rebase/merge to avoid conflicts

**Comment by fedde-s** [comment]
@rnugraha: done.

**Pull request merged**
